version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: donut
      MYSQL_PASSWORD: donut
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

  frontend_home:
    build: ./frontend/home
    container_name: frontend_home_container
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/home:/app
    depends_on:
      - backend

volumes:
  mysql_data:
